name: enemprep_flutter
description: ENEM Prep AI application
version: 0.0.4+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_markdown: ^0.6.18
  fl_chart: ^0.65.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^13.2.0
  
  # State Management
  provider: ^6.1.1
  
  # Data Handling
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  http: ^1.1.2
  crypto: ^3.0.3
  
  # Camera and Image
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  image: ^4.1.3
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2
  logger: ^2.0.2+1

  # Add url_launcher dependency
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/json/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
